#!/bin/bash
# vim:foldmethod=marker
# vim:foldmarker=#{{{,#}}}

#{{{ search and navigation
alias fe="$FILE_EXPLORER ."
alias mkd="mkdir -p"
# search
alias grep="grep --color=auto"
alias rg="rg --sort path"
alias gals='alias | rg '
alias c="clear"
# listings
alias \
  ls="eza --color=auto --group-directories-first --icons=auto" \
  l='ls' \
  la='ls -a' \
  l.='ls -a | rg "^\."' \
  ll='ls -l' \
  lt='ls -T' \
  lla='ls -la' \
  lta='ls -Ta'
alias tree="tree -C"
# jump fzf
jf() { cd "$(fd -td | fzf --preview 'eza --tree --color=always {}')" || return; }
j.() { cd "$(fd -H -I -td | fzf --preview 'eza --tree --color=always {}')" || return; }
#}}}

#{{{ files
# general
alias \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi"
# editor
alias \
  e="$EDITOR" \
  v="$EDITOR" \
  o="xdg-open" \
  z="zathura"
# rg into a vim quicklist
vg () {
  fst=$1
  shift
  rg --vimgrep "$fst" $@ | $EDITOR -q - 
}
# edit fzf
ef() { fd . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % $EDITOR %; }
e.() { fd -H -I . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % $EDITOR %; }
# zathura fzf
zf() { fd . | fzf | xargs -r -I % sh -c 'zathura "$1" >/dev/null 2>&1 &' _ %; }
# library fzf
lb() { fd -L . "$HOME"/library | fzf | xargs -r -I % sh -c 'zathura "$1" >/dev/null 2>&1 &' _ %; }
# xdg-open fzf
of() { fd . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % xdg-open %; }
o.() { fd -H -I . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % xdg-open %; }
#}}}

#{{{ processes
alias prg="ps x | rg $1"
alias ka="killall"
#}}}

#{{{ zellij
alias \
  s="zellij-sessionizer.sh" \
  za="zellij a" \
  zl="zellij ls" \
  zrm="zellij delete-session" \
  zrma="zellij delete-all-sessions"
#}}}

#{{{ tmux
alias \
  t="tmux-sessionizer.sh" \
  tl='tmux list-sessions' \
  ta='tmux attach-session -t'
#}}}

#{{{ git
alias lg="lazygit"
#}}}

#{{{ docker
alias d='docker'
alias dc='docker compose'
alias dcb='docker-compose build'
alias dcdn='docker-compose down'
alias dce='docker-compose exec'
alias dck='docker-compose kill'
alias dcl='docker-compose logs'
alias dclF='docker-compose logs -f --tail 0'
alias dclf='docker-compose logs -f'
alias dco=docker-compose
alias dcps='docker-compose ps'
alias dcpull='docker-compose pull'
alias dcr='docker-compose run'
alias dcrestart='docker-compose restart'
alias dcrm='docker-compose rm'
alias dcstart='docker-compose start'
alias dcstop='docker-compose stop'
alias dcup='docker-compose up'
alias dcupb='docker-compose up --build'
alias dcupd='docker-compose up -d'
alias dcupdb='docker-compose up -d --build'
#}}}

#{{{ systemd
# systemctl
alias \
  sysd="systemctl" \
  sysd_failed="systemctl list-units --failed" \
  sysd_status="systemctl list-unit-files --type=service" \
  sysd_user_services="systemctl --user list-units --type=service" \
  sysd_generate_serv_list="systemctl list-units --state=running | grep -v systemd | awk '{print $1}' | grep service > daemon_list_${today}.txt" \
  systimers="systemctl list-timers"
# journalctl
alias jctl="journalctl -p 3 -xb"
#}}}

#{{{ cloud sync
# rclone proton sync
alias \
  syn="systemctl --user start rclone-bisync.service" \
  synj="journalctl --user -xeu rclone-bisync.service" \
  synst="systemctl --user status rclone-bisync.service" \
  syntt="systemctl --user status rclone-bisync.timer" \
  rsyn='rclone-bisync.sh --resync'
#}}}

#{{{ packages
# pkg manager (paru, yay or pacman)
alias p="$PKG_MANAGER"
# update
alias \
  u='p -Syu' \
  unc='u --noconfirm' \
  uf='p -Syyu'
# add/remove
alias \
  add="p -S" \
  rmp="p -Rns"
# clean orphaned packages
alias cleanup='p -Rns $(pacman -Qtdq)'
# pkg list
today=$(date +"%Y-%m-%d")
alias pkglist_1="p -Qqe > pkglist_explicitly_installed_${today}.txt"                                            # explicitly installed packages.
alias pkglist_2="p -Qq | awk '{print $1}' > pkglist_all_${today}.txt"                                           # list all packages.
alias pkglist_3="p -Qqet | awk '{print $1}' > pkglist_explicitly_installed_not_required_by_others_${today}.txt" # explicitly installed packages that are not required by any other package.
alias pkglist_versions="p -Qe > pkglist_versions_${today}.txt"                                                  # list explicitly installed packages w/ version number.
alias pkgaur="p -Qqem > foreignpkglist_${today}.txt"                                                            # list packages that were not found in the sync database (AUR).
#}}}

#{{{ mirrors
alias \
  mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
  mirrord="sudo reflector --latest 30 --number 10 --sort delay --save /etc/pacman.d/mirrorlist" \
  mirrors="sudo reflector --latest 30 --number 10 --sort score --save /etc/pacman.d/mirrorlist" \
  mirrora="sudo reflector --latest 30 --number 10 --sort age --save /etc/pacman.d/mirrorlist" \
  mirrorx="sudo reflector --age 6 --latest 20  --fastest 20 --threads 5 --sort rate --protocol https --save /etc/pacman.d/mirrorlist" \
  mirrorxx="sudo reflector --age 6 --latest 20  --fastest 20 --threads 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist"
#}}}

#{{{ sysadmin
alias df='df -h'                            # human-readable sizes
alias disk_usage='du -csh -- */ | sort -rh' # list the folders by usage
alias sysinfo='inxi -Fxz'                   # shows overall system information
alias hw="hwinfo --short"                   # hardware info --short
alias free="free -mth"                      # ram + swap usage
alias ip="ip -color=auto"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
se() { du -a $HOME/.local/bin/* | awk '{print $2}' | fzf | xargs -r $EDITOR; } # edit scrips in ~/.local/bin
#}}}

#{{{ misc
alias \
  bc="bc -ql" \
  yt="yt-dlp --embed-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner" \
  update-fc="sudo fc-cache -fv" \
  wget="wget -c" \
  hypr="Hyprland"
#}}}

#{{{ rust
alias \
  rp='rustup' \
  rman='rustup man' \
  rbook='rustup doc --book' \
  rcargo='rustup doc --cargo' \
  rstd='rustup doc --cargo' \
  rref='rustup doc --reference' \
  rexample='rustup doc --rust-by-example'
#}}}

#{{{ automatic sudo
for command in mount umount pacman updatedb su shutdown poweroff reboot; do
  alias $command="sudo $command"
done
unset command
#}}}

#{{{ number conversion
d2b() {
  echo "obase=2; $1" | bc
}
d2x() {
  echo "obase=16; $1" | bc
}
x2d() {
  echo $((16#$1))
}
b2d() {
  echo $((2#$1))
}
x2b() {
  echo "obase=2; $(x2d $1)" | bc
}
#}}}
