#!/bin/bash
#vim:foldmethod=marker
#vim:foldmarker=#{{{,#}}}

#{{{ search and navigation
alias fe="$FILE_EXPLORER ."
alias mkd="mkdir -p"
alias grep="grep --color=auto"
alias rg="rg --sort path"
alias c="clear"
alias \
  ls="eza --color=always --group-directories-first --icons" \
  l='ls' \
  la='ls -a' \
  l.='ls -a | rg -E "^\."' \
  ll='ls -l' \
  lt='eza -T --color=always --group-directories-first --icons=auto' \
  lla='ls -la' \
  lta='eza -Ta --color=always --group-directories-first --icons=auto'
alias tree="tree -C"
# jump fzf
jf() { cd "$(fd -td | fzf --preview 'eza --tree --color=always {}')" || return; }
jfh() { cd "$(fd -H -I -td | fzf --preview 'eza --tree --color=always {}')" || return; }
#}}}

#{{{ files
# general
alias \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi"
# editor
alias \
  e="$EDITOR" \
  v="$EDITOR" \
  o="xdg-open" \
  z="zathura"
# file fzf
vf() { fd . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % $EDITOR %; }
vfh() { fd -H -I . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % $EDITOR %; }
# zathura fzf
zf() { fd . | fzf | xargs -r -I % sh -c 'zathura "$1" >/dev/null 2>&1 &' _ %; }
# library fzf
zfl() { fd -L . "$HOME"/library | fzf | xargs -r -I % sh -c 'zathura "$1" >/dev/null 2>&1 &' _ %; }
# xdg-open fzf
of() { fd . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % xdg-open %; }
ofh() { fd -H -I . | fzf --preview 'bat -n --color=always --line-range :500 {}' | xargs -r -I % xdg-open %; }
#}}}

#{{{ processes
alias prg="ps x | rg $1"
alias ka="killall"
#}}}

#{{{ projects
# tmux
alias \
  t="tmux-sessionizer.sh" \
  tl='tmux list-sessions' \
  ta='tmux attach-session -t'

# git
alias lg="lazygit"
#}}}

#{{{ systemd
# systemctl
alias \
  sysd="systemctl" \
  sysd_failed="systemctl list-units --failed" \
  sysd_status="systemctl list-unit-files --type=service" \
  sysd_user_services="systemctl --user list-units --type=service" \
  sysd_generate_serv_list="systemctl list-units --state=running | grep -v systemd | awk '{print $1}' | grep service > daemon_list_${today}.txt" \
  systimers="systemctl list-timers"

# journalctl
alias jctl="journalctl -p 3 -xb"
#}}}

#{{{ cloud sync
## rclone proton sync
alias \
  syn="systemctl --user start rclone-bisync.service" \
  synj="journalctl --user -xeu rclone-bisync.service" \
  synst="systemctl --user status rclone-bisync.service" \
  syntt="systemctl --user status rclone-bisync.timer" \
  cleansync='rclone-bisync.sh false true'
#}}}

#{{{ packages
# pkg manager (paru, yay or pacman)
alias p="$PKG_MANAGER"
# update
alias \
  u='p -Syu' \
  uf='p -Syyu'
# add/remove
alias \
  add="p -S" \
  rmp="p -Rns"

# clean orphaned packages
alias cleanup='p -Rns $(pacman -Qtdq)'

today=$(date +"%Y-%m-%d")
alias pkglist_1="p -Qqe > pkglist_explicitly_installed_${today}.txt"                                            # explicitly installed packages.
alias pkglist_2="p -Qq | awk '{print $1}' > pkglist_all_${today}.txt"                                           # list all packages.
alias pkglist_3="p -Qqet | awk '{print $1}' > pkglist_explicitly_installed_not_required_by_others_${today}.txt" # explicitly installed packages that are not required by any other package.
alias pkglist_versions="p -Qe > pkglist_versions_${today}.txt"                                                  # list explicitly installed packages w/ version number.
alias pkgaur="p -Qqem > foreignpkglist_${today}.txt"                                                            # list packages that were not found in the sync database (AUR).
#}}}

#{{{ mirrors
alias \
  mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
  mirrord="sudo reflector --latest 30 --number 10 --sort delay --save /etc/pacman.d/mirrorlist" \
  mirrors="sudo reflector --latest 30 --number 10 --sort score --save /etc/pacman.d/mirrorlist" \
  mirrora="sudo reflector --latest 30 --number 10 --sort age --save /etc/pacman.d/mirrorlist" \
  mirrorx="sudo reflector --age 6 --latest 20  --fastest 20 --threads 5 --sort rate --protocol https --save /etc/pacman.d/mirrorlist" \
  mirrorxx="sudo reflector --age 6 --latest 20  --fastest 20 --threads 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist"
#}}}

#{{{ sysadmin
alias df='df -h'                            # human-readable sizes
alias disk_usage='du -csh -- */ | sort -rh' # List the folders o
alias sysinfo='inxi -Fxz'                   # Shows overall system information
alias hw="hwinfo --short"                   # hardware info --short
alias free="free -mt"
alias ip="ip -color=auto"
alias probe="doas -E hw-probe -all -upload"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
# edit scrips in ~/.local/bin
se() { du -a $HOME/.local/bin/* | awk '{print $2}' | fzf | xargs -r $EDITOR; }
#}}}

#{{{ misc
alias \
  bc="bc -ql" \
  yt="yt-dlp --embed-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner" \
  update-fc="sudo fc-cache -fv" \
  wget="wget -c"
#}}}

#{{{ docker
alias dc='docker' \
  dce='docker compose' \
  dcex='docker compose exec -it' \
  dcx='docker exec -it' \
  dci='docker image' \
  dcc='docker container' \
  dcn='docker network' \
  dcv='docker volume' \
  dcps='docker compose ps'
#}}}

#{{{ rust
alias rustbook='rustup doc --book'
alias rp='rustup'
alias rman='rustup man'
#}}}

#{{{ automatic sudo
for command in mount umount pacman updatedb su shutdown poweroff reboot; do
  alias $command="sudo $command"
done
unset command
#}}}

source "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/shortcutrc
